--[LOCATION]:[Workspace.ExampleBeatmap]
-- Last update: 20-08-2022 [Aug 20, 2022]
-- Note: Custom audio may be unavailable, you can only use audio upload from VtntGaming and Roblox .-.

return[[
osu file format v14

[RobloxData]
RblxCreatorUserID: 1241445502
RblxSoundID: 0
SoundOffset: 0
BackgroundImageId: 0
SongSpeed: 1
SongPitch: 1
BeatmapVolume: 1
WeirdSliderAlert: 0
SliderCrashAlert: 0
RblxSoundID2: 0
CustomSoundFile:C:\Program Files (x86)\Roblox\Versions\version-1a73dfe7956a4343\content\osuRoVer\map\Marianne\audio.mp3
CustomBackgroundFile:C:\Program Files (x86)\Roblox\Versions\version-1a73dfe7956a4343\content\osuRoVer\map\Marianne\background.jpg


[General]
AudioFilename: Audio.mp3
AudioLeadIn: 0
PreviewTime: 0
Countdown: 0
SampleSet: Normal
StackLeniency: 0.4
Mode: 0
LetterboxInBreaks: 0
WidescreenStoryboard: 0

[Editor]
Bookmarks: 0
DistanceSpacing: 1
BeatDivisor: 4
GridSize: 4
TimelineZoom: 1

[Metadata]
Title:Example
TitleUnicode:Example
Artist:VtntGaming
ArtistUnicode:VtntGaming
Creator:VtntGaming
Version:Example
Source:
Tags:osu!RoVer
BeatmapID:75359
BeatmapSetID:27154

[Difficulty]
HPDrainRate:5
CircleSize:4
OverallDifficulty:5
ApproachRate:5
SliderMultiplier:1
SliderTickRate:1

[Events]
//Background and Video events
0,0,"background.jpg",0,0
//Break Periods
2,1000,2000
//Storyboard Layer 0 (Background)
//Storyboard Layer 1 (Fail)
//Storyboard Layer 2 (Pass)
//Storyboard Layer 3 (Foreground)
//Storyboard Sound Samples

[TimingPoints]
1100,12.116666666667,4,1,1,5,1,0
1200,-100,4,1,1,60,0,0

[Colours]
Combo1 : 255,255,255
Combo2 : 255,255,255
Combo3 : 255,255,255
Combo4 : 255,255,255

[HitObjects]
256,192,1100,12,0,3772,2:0:0:0:
]]